language: go
go:
- '1.8'
- '1.9'
- 1.10.x
before_install:
- go get -u github.com/axw/gocov/gocov
- go get -u github.com/mattn/goveralls
- go get -u golang.org/x/tools/cmd/cover
- go get -u github.com/modocache/gover
- go get -u github.com/fzipp/gocyclo
before_script:
- if [ -n $(go fmt)" ]; then echo 'Code is not formatted with "go gmt"'; false; fi
- go tool vet `go list ./... | grep -v 'vendor' | sed -e "s,^,$GOPATH/src/,;s,.*:,,"`
- gocyclo -over 15 `find . -iname '*.go' | grep -v 'vendor' | grep -v '_test.go'`
script:
- go list ./... | grep -v vendor | xargs -n1 -I {} -P 4 go test -v -covermode=count
  -coverprofile=../../../{}/profile.coverprofile {}
- go build
after_success:
- gover
- goveralls -service=travis-ci -coverprofile=gover.coverprofile -repotoken $COVERALLS_TOKEN
env:
  global:
    secure: w/6fEl0ANROjdGI1aAFefYJeaqntN1MsFQbrbdmM8oTc2Bv+CxQBdQGqyUxVIo1PgEInVla2hg+PRSdkBFnVHPzoZErmhqYH1YosvN1dldn9ikyMDKZ1zm5ZayTHoYlkyW9kyCy5VsoglxS3uOGWYL5JPfE+IVXnFvlhb4PhXpdfcGnVJaFGKdFmxtr4asp3nawTVZyZbvfWps6NnJyu/HrN2YGntjl4JFHaS39evkRI2/puleifImkQpuobsW+V6/AztE+6jZaNmc+Jaz5dFfoQQD0c2ttiswGWJHC+dflSe5O0A/LdBqgFVN5+WCQ9nGCMe/6sqF8ifwDt+P6DDnmg95WxcvaNVZm5zHgeugsFSGyV1wR8Vce6RnBLK4jRen5y+Wpfltgn5IETicLnw+ecY0Yk3WKGW3vPCVWVCzcMJzgf6mrL0CIRrIsdKAP40XtD5Jel2/MJNUud+VZ+y70pnuaA3oShs9kfnCwRN3kEDMTujNTdM3xq/dA+95FlO9eA9jK3IkUuhk/K3fQkEaLMOfxILx0ADF/U9v9HcdwwE8VsD6xsudJF4W5lDUs/dCeThN5OpGlvZm3p91zZrYuElj9gf1fq79e5VYyuGQcVq1VVe3nNE2DEANrQDQQeRzWIHZR5plhQhYX/IUPudqyAbeyzSysc28EyNOpYyF0=
